### ISSUE TITLE
Failed to run engine

### ISSUE THREAD

**Issue by AlienKevin** [dribnet/perceptionengines#3]
Hi, I'm a beginner in ML and Python. I tried to use the plan image command in README:
```
python plan_image.py \
  --outdir outputs/birdhouse_1060 \
  --target-class birdhouse \
  --random-seed 1060 \
  --renderer lines1 \
  --num-lines 30
```
but it gives me an error like this:
```
Traceback (most recent call last):
  File "plan_image.py", line 585, in <module>
    main()
  File "plan_image.py", line 498, in main
    class_mapping = open_class_mapping()
  File "/home/kevin/perceptionengines/utils.py", line 63, in open_class_mapping
    with open(class_file) as json_data:
IOError: [Errno 2] No such file or directory: '/home/kevin/.keras/models/imagenet_class_index.json'
```
Could someone help me? Thanks. I'm using python 2.7.17 on Ubuntu 18.04 LTS in wsl2 of Windows 10.

**Comment by shadaron** [comment]
I got that error as well. I solved it by downloading the required file: https://github.com/raghakot/keras-vis/blob/master/resources/imagenet_class_index.json and placing it in the required destination ( system folder .keras). Hope that helps

**Comment by AlienKevin** [comment]
Thanks for the solution. I successfully fix this error but got a new one like this:
```
Using TensorFlow backend.
Threshold is 30 attempts to 0.9999
----> Processing [u'birdhouse']
('Requested networks: ', ['inceptionv3', 'resnet50', 'vgg19', 'xception'])
Setting up inceptionv3
==> Failed to load supporting class inceptionv3
==> Check that package inceptionv3 is installed
(exception was: No module named scoring.inceptionv3)
```
How can I install inceptionv3. Are there more dependencies that I need?

**Comment by AlienKevin** [comment]
I figured out a way to overcome this problem by using python 3:
```
python3 plan_image.py \
  --outdir outputs/birdhouse_1060 \
  --target-class birdhouse \
  --random-seed 1060 \
  --renderer lines1 \
  --num-lines 30
```
